### ISSUE TITLE
Detect non-working escapes in regexp strings

### ISSUE THREAD

**Issue by doublep** [mattiase/trawl#11]
Currently the linter finds no problems in a form like this:

    (re-search-forward "\.foo")

Here the `\` does nothing, because it is eaten for Elisp string escaping purposes. But the intent was most likely to regexp-escape the dot, i.e. use "\\.".

This is already caught by normal syntax highlighting in Lisp (highlighted as a warning, e.g. red), but I guess it wouldn't hurt if the linter aimed at regular expression validation would also warn about such things.

**Comment by mattiase** [comment]
Very much agree, and I have a tool that locates these mistakes which has been used to cleanse the Emacs source tree; I've attached a snapshot. It's quite fast but a bit rough at the edges; try
`emacs -l miscape -f miscape-batch file1.el file2.el ...` or use it with `find`.

It would be useful to have it integrated with relint since it's such a common mistake in regexps, as you noted. However, it's unclear how this should be done: not all string literals in a buffer are necessarily parts of a regexp. Conversely, locating all literals used in the formation of a regexp isn't straightforward either because of how the relint evaluation engine works.

Perhaps it's not a terrible thing to have relint complain about backslashes in non-regexp strings, since the user probably doesn't mind fixing those as well. What do you think?

[miscape.el.gz](https://github.com/mattiase/relint/files/4779468/miscape.el.gz)

**Comment by doublep** [comment]
> Perhaps it's not a terrible thing to have relint complain about backslashes in non-regexp strings, since the user probably doesn't mind fixing those as well.

I think it would be better than the current state. Maybe limiting this only to backslashes before regexp-special characters like `.` or `>`.

Or maybe it is still possible to only complain about strings you use otherwise.  I.e. if you handle forms like `(re-search-forward EXPR ...)`, would it not be possible to only check string literals used anywhere inside the `EXPR`? As I understand, to validate regexp you need to compute the final value (if it can be determined at compilation time), but maybe you can also collect all encountered literals along and check them for suspiciously pointless escape sequences?

**Comment by mattiase** [comment]
Well, relint uses the standard Lisp reader which discards any superfluous backslashes; only the semantic string value is returned. While it would certainly be possible to write a custom reader that preserves the original source text and location as metadata, it would be much slower, as well as less convenient to traverse. This is why miscape has to work on the lexical level directly.

Having to keep track of exactly what strings actually end up as part of a regexp would also slow down and complicate the evaluation engine substantially.

One possibility is to clean up miscape as a special-purpose linter, so that people can use it along with relint and other checkers. Another is integrating miscape into relint and see what happens; I'll give it a go.

**Comment by doublep** [comment]
> While it would certainly be possible to write a custom reader that preserves the original source text and location as metadata, it would be much slower, as well as less convenient to traverse.

Since you already have error positions, you could use the standard reader as now, traverse its result and then re-read with a custom reader from given position only when you actually need to look for suspiciously escaped strings, i.e. when you have an expression that evaluates to something you treat as regexp. (You sort of already do this for `relint suppression: REGEXP` comments.) Though this is admittedly much harder — maybe not worth it to add a custom reader just for this.

**Comment by mattiase** [comment]
Yes, but we currently only go back to looking at the source buffer when required for determining the exact location of an error, and being slow in that case is quite acceptable. We would need to do it routinely for everything, which would not only be much more expensive but also need to thread the information through the evaluator.

In addition, botched backslashing can do damage in strings that aren't part of a regexp, and it would be a shame to detect those without telling the user about it.

**Comment by mattiase** [comment]
Would you try the `miscape` branch of relint? It basically bolts the two checkers together with some performance tuning. Some notes:

* The output from the two checkers now come in sequence; they should probably be sorted together, in ascending order by location.
* Currently, all doc strings are exempt from backslash errors to cut down on the false positives, as are errors at the beginning of a line in string literals that span multiple lines. This can be tuned.

**Comment by doublep** [comment]
Seems to work fine here. I have only one complaint about this part of code:

    +(defconst relint--miscape-ignore-left-round-bracket nil
    +  "Whether to ignore specifically `\\(' in doc strings.")
    +
    +(defconst relint--miscape-ignore-all-doc-strings t
    +  "Whether to ignore all stray backslashes in doc strings.")

Please don't mark variables *meant* to be changeable as "constants". And consider making them public (i.e. replacing `--` with `-`) if you don't provide an indirect way to change these settings. As it stands, it is not possible to change things that "can be tuned" without diving into package-private details.

**Comment by mattiase** [comment]
Thanks for testing! Some improvements have been made after more thorough testing; if it works all right for you, it will be merged and released.

Regarding the defconsts: we may disagree about it, but I think a programmer is well in his right to introduce constants for tuning his own algorithms, especially when they are clearly private to the implementation. Not everything needs to be made public, in particular with all the extra work this entails.

In this case, the constants were dispensed with anyway after fine-tuning the false-positive rejection, having scanned almost 5000 .el files from various sources.

**Comment by doublep** [comment]
I thought you were going to keep them for users to configure the linter (that's how I understood "can be tuned"). If they are gone completely it's fine.

**Comment by mattiase** [comment]
Oh, sorry, a misunderstanding then. No, there aren't any plans to introduce configuration by the user at this point.

**Comment by mattiase** [comment]
Merged to master. It will be pushed to GNU ELPA shortly.
