### ISSUE TITLE
Mistake in regexp for font-lock-add-keywords not detected

### ISSUE THREAD

**Issue by federicotdn** [mattiase/trawl#8]
Hi! Thanks for creating this project. I've been using it to add an extra linting stage to a project of mine, and I realized that it picked up a mistake on a variable I declared:
```
verb.el:288:36: In verb--http-header-regexp: Literal `-' not first or last in character alternative (pos 13)
  "^\\([[:alnum:]-.]+:\\).*$"
   ..............^
```
But when I did the same mistake in a call to `font-lock-add-keywords`, it didn't detect it.

Related question, how does relint decide if a string is a regexp or not? I think that information would be really useful to have in the README.

Thanks!

**Comment by mattiase** [comment]
Thank you – this kind of report is very welcome. I've added detection of regexps in calls to font-lock-add-keywords, as well as mutation of font-lock-defaults for good measure.

To answer your other question: finding regexps is the main business of relint, but in short: it guesses. It knows about some built-in functions that take regexp arguments, like string-match, and checks calls to those. It also looks at names of functions and variables: for instance, it assumes that anything ending in '-regexp' is likely to be a regexp. There are more heuristics used in specialised cases.

Since the heuristics keep evolving, I'm not sure if it's worth providing more detail in the README than is currently there: 'ad-hoc rules' sums it up rather accurately, I'm afraid. A lot of the machinery is dedicated to the (partial) evaluation of expressions without actually running the code. There is also the constraint that it has to be fast, or nobody will use it!

**Comment by federicotdn** [comment]
Aah ok, I see. Well, thanks for the explanation anyways, and for the fix!

**Comment by basil-conto** [comment]
On the topic of balancing Font Lock awareness and speed/simplicity, should it be Relint's business to detect keywords that form subsets of preceding keywords?  Here's a simple example from the `m4-mode` that ships with Emacs:
```el
(defvar m4-font-lock-keywords
  (eval-when-compile
    `(...
      ("\\$[*#@0-9]" . font-lock-variable-name-face)
      ("\\$@"        . font-lock-variable-name-face)
      ("\\$\\*"      . font-lock-variable-name-face)
      ...))
  "Default `font-lock-keywords' for M4 mode.")
```
I ask because these three entries should be equivalent to the single entry
```el
("\\$[*#@0-9]\\|\\$@\\|\\$\\*" . font-lock-variable-name-face)
```
which Relint already diagnoses.

The main complication in adding such Font Lock awareness is the need to check for OVERRIDE or similar keyword elements, which may complicate the facespec equivalence checking.

**Comment by mattiase** [comment]
Thanks for the suggestion. I tried a quick hack to see roughly how widespread this issue would be and the answer seems to be not very much, and as you say the complexity to avoid false positives would probably not be worth the benefits.

In particular, users often build font-lock-keyword regexps in intricate ways so I fear it would rapidly turn into warnings that are even more mystifying than usual, and/or difficult to make go away.

**Comment by basil-conto** [comment]
Agreed. Besides, I imagine redundancies in keyword regexps to be one of the smaller issues faced by authors of Font Lock entries, with the larger issues already addressed by other tools such as Font Lock Studio & co.
